version: '3'
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "8000:80"
      - "8001:8001"

  app-a.envoy:
    build:
      context: ./app-a
      dockerfile: Dockerfile-envoy
    networks:
      envoymesh:
        aliases:
          - app-a.envoy
    environment:
      - SERVICE_NAME=a

  app-a:
    build:
      context: ./app-a
      dockerfile: Dockerfile-app
    networks:
      envoymesh:
        aliases:
          - app-a
    environment:
      - SERVICE_NAME=a
      - REDIS_HOST=app-a-redis

  app-a-redis:
    image: redis:latest
    networks:
      envoymesh:
        aliases:
          - app-a-redis

  app-b.envoy:
    build:
      context: ./app-b
      dockerfile: Dockerfile-envoy
    networks:
      envoymesh:
        aliases:
          - app-b.envoy
    environment:
      - SERVICE_NAME=b

  app-b:
    build:
      context: ./app-b
      dockerfile: Dockerfile-app
    networks:
      envoymesh:
        aliases:
          - app-b
    environment:
      - SERVICE_NAME=b
      - REDIS_HOST=app-b-redis

  app-b-redis:
    image: redis:latest
    networks:
      envoymesh:
        aliases:
          - app-b-redis

networks:
  envoymesh: {}
